name = "newsnow-project"  # 你的项目名称
type = "javascript"
pages_build_output_dir = "dist/output/public"

[[d1_databases]]
binding = "NEWSNOW_DB"
database_name = "newsnow_db"  # 替换为你创建的数据库名称
database_id = "edfbd6e0-e763-485a-9f30-56cd696ff285"      # 替换为你创建的数据库 ID
